name: Run Selenium Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - tests/test_login.py
          - tests/test_checkout.py

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest allure-pytest

      - name: Download ChromeDriver and Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set ChromeDriver path
        run: |
          echo "CHROME_BIN=$(which google-chrome)" >> $GITHUB_ENV
          echo "CHROMEDRIVER=$(which chromedriver)" >> $GITHUB_ENV

      - name: Run Pytest and generate Allure results
        run: pytest --alluredir=reports

      - name: Upload Allure Results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: reports
